apiVersion: batch/v1
kind: Job

metadata:
  generateName: prisma-migration-

spec:
  backoffLimit: 3

  ttlSecondsAfterFinished: 300

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: prisma-migration

          image: ghcr.io/gibsonjesus1/pharmacy-backend:latest

          imagePullPolicy: Always

          command:
            - npx
            - prisma
            - migrate
            - deploy

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pharmacy-secret
                  key: DATABASE_URL