apiVersion: v1

kind: Secret

metadata:
  name: pharmacy-secret

type: Opaque

stringData:
  DATABASE_USER: postgres

  DATABASE_PASSWORD: postgres

  DATABASE_URL: postgresql://postgres:postgres@postgres-service:5432/pharmacy

  JWT_SECRET: supersecret